apiVersion: dataplane.juniper.net/v1alpha1
kind: Vrouter
metadata:
  annotations:
    conversion.spec.agent.default.fabricRpfCheckDisable: "true"
    conversion.spec.dpdk.smartnicConfig: '{}'
    conversion.spec.terminationGracePeriodSeconds: "60"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"dataplane.juniper.net/v1","kind":"Vrouter","metadata":{"annotations":{},"name":"contrail-vrouter-nodes","namespace":"contrail"},"spec":{"agent":{"default":{"fabricRpfCheckDisable":true,"logLevel":"SYS_INFO","xmppAuthEnable":false},"sandesh":{"introspectSslEnable":false,"sandeshSslEnable":false}},"agentModeType":"dpdk","common":{"affinity":{"nodeAffinity":{"requiredDuringSchedulingIgnoredDuringExecution":{"nodeSelectorTerms":[{"matchExpressions":[{"key":"node-role.kubernetes.io/control-plane","operator":"DoesNotExist"}]}]}}},"containers":[{"image":"10.108.30.10:5000/atom-docker/cn2/bazel-build/dev/x86_64/contrail-vrouter-agent:master","imagePullPolicy":"IfNotPresent","livenessProbe":{"failureThreshold":3,"httpGet":{"host":"127.0.0.1","path":"/vrouter-health-check","port":9091},"initialDelaySeconds":10,"periodSeconds":20,"successThreshold":1,"timeoutSeconds":5},"name":"contrail-vrouter-agent","startupProbe":{"failureThreshold":3,"httpGet":{"host":"127.0.0.1","path":"/vrouter-health-check","port":9091},"initialDelaySeconds":10,"periodSeconds":20,"successThreshold":1,"timeoutSeconds":5}},{"image":"10.108.30.10:5000/atom-docker/cn2/bazel-build/dev/x86_64/contrail-vrouter-dpdk:master","imagePullPolicy":"IfNotPresent","name":"contrail-vrouter-agent-dpdk","resources":{"limits":{"hugepages-1Gi":"6Gi","memory":"6Gi"},"requests":{"hugepages-1Gi":"6Gi","memory":"6Gi"}}},{"env":[{"name":"TELEMETRY_EXPORTER_SCHEME","value":"http"},{"name":"INTROSPECT_SCHEME","value":"http"}],"image":"10.108.30.10:5000/atom-docker/cn2/bazel-build/dev/x86_64/contrail-telemetry-exporter:master","imagePullPolicy":"IfNotPresent","name":"contrail-vrouter-telemetry-exporter"}],"initContainers":[{"args":["sysctl -w net.ipv6.conf.default.addr_gen_mode=0 \u0026\u0026 sysctl -w net.ipv6.conf.all.addr_gen_mode=0 \u0026\u0026 sysctl -w net.ipv6.conf.default.autoconf=0 \u0026\u0026 sysctl -w net.ipv6.conf.all.autoconf=0 \u0026\u0026 echo -e \"\\nSuccessfully loaded kernel parameter using sysctl cli\\n\" || echo -e \"\\nError in loading kernel parameter using sysctl cli\\n\"; modprobe tun \u0026\u0026 modprobe ipip \u0026\u0026 modprobe ip_tunnel \u0026\u0026 modprobe ip6_tunnel \u0026\u0026 modprobe mpls_gso \u0026\u0026 modprobe mpls_router \u0026\u0026 modprobe mpls_iptunnel \u0026\u0026 modprobe vrf \u0026\u0026 modprobe vxlan \u0026\u0026 modprobe fou \u0026\u0026 modprobe fou6 \u0026\u0026 echo -e \"\\nSuccessfully loaded kernel modules\\n\"|| echo -e \"\\nError in loadinfg kernel modules. Check whether kernel modules packages are installed or not.\\nIf running OS is Ubuntu, Run following command and reboot  to enable kernel modules.\\nsudo apt install linux-generic -y \\n sudo apt install --reinstall linux-image-$(uname -r) -y; \\n sudo apt install --reinstall linux-modules-$(uname -r) -y;\\n sudo apt install --reinstall linux-modules-extra-$(uname -r) -y; \\n\" ; set -o pipefail \u0026\u0026 python3 -u crpdconfig_generator/crpdconfig_generator.py evpn | tee -a \"/var/log/contrail/cleanup.log\" ;"],"command":["/bin/sh","-c"],"env":[{"name":"NODE_NAME","valueFrom":{"fieldRef":{"fieldPath":"spec.nodeName"}}},{"name":"PYTHONUNBUFFERED","value":"1"}],"image":"svl-artifactory.juniper.net/junos-docker-local/warthog/amd64/crpdconfig-generator:v21","name":"jcnr-evpn-conf","securityContext":{"capabilities":{"add":["SYS_MODULE","NET_ADMIN","SYS_PTRACE"]},"privileged":true,"runAsUser":0},"volumeMounts":[{"mountPath":"/etc/podinfo","name":"podinfo"},{"mountPath":"/var/lib/contrail","name":"var-lib-contrail"},{"mountPath":"/var/run","name":"var-run"},{"mountPath":"/var/run/contrail","name":"var-run-contrail"},{"mountPath":"/etc/contrail","name":"config-volume"},{"mountPath":"/var/crash","name":"var-crashes"},{"mountPath":"/var/log/contrail","name":"var-log-contrail"},{"mountPath":"/lib/modules","name":"lib-modules"}]},{"image":"10.108.30.10:5000/atom-docker/cn2/bazel-build/dev/x86_64/contrail-init:master","imagePullPolicy":"IfNotPresent","name":"contrail-init"},{"image":"10.108.30.10:5000/atom-docker/cn2/bazel-build/dev/x86_64/contrail-vrouter-kernel-init-dpdk:master","imagePullPolicy":"IfNotPresent","name":"contrail-vrouter-kernel-init-dpdk"}]},"coreFilePath":"/var/crash","corePattern":"","dpdk":{"cpuCoreMask":"2,3","dpdkCommandAdditionalArgs":"--yield_option 0","dpdkCtrlThreadMask":"","dpdkUioDriver":"vfio-pci","hugePages":null,"hugePagesDir":"/dev/hugepages","l2TableAgeout":60,"l2TableSize":"10240","mtu":9000,"serviceCoreMask":""},"headlessMode":true,"installCni":false,"interfaceLayer":"l3","interfaces":[{"ddp":"auto","level":"l3","name":"enp3s0","type":"fabric"}],"logPath":"/var/log/jcnr/","qosEnable":false,"restoreInterfaces":false,"stormControlProfiles":{"rate_limit_pf1":{"bandwidth":{"level":0}}}}}
  creationTimestamp: "2023-12-27T09:47:54Z"
  name: contrail-vrouter-nodes
  namespace: contrail
spec:
  agent:
    agentTestFramework: {}
    controlNode: {}
    crypt: {}
    default:
      agentBaseDirectory: /var/lib/contrail
      coreDumpFilter: "0x13"
      flowCacheTimeout: 0
      grpcServerPort: 50052
      httpServerIp: 0.0.0.0
      httpServerPort: 8085
      logFile: /var/log/contrail/contrail-vrouter-agent.log
      logLevel: SYS_INFO
      mirrorClientPort: 8097
      pkt0TxBuffers: 1000
      restPort: 9091
      sandeshSendRateLimit: 0
      staleInterfaceCleanupTimeout: 60
      syslogFacility: LOG_LOCAL0
      tunnelType: MPLSoGRE
      vmiVMVnUveInterval: 30
      vrObjectHighWatermark: 80
      xmppAuthEnable: false
      xmppCaCert: /etc/contrail/ssl/certs/ca-cert.pem
      xmppServerCert: /etc/contrail/ssl/certs/server.pem
      xmppServerKey: /etc/contrail/ssl/private/server-privkey.pem
    dns: {}
    flows: {}
    hypervisor: {}
    llgr: {}
    macLearning: {}
    metadata: {}
    nexthopServer: {}
    qos: {}
    restart: {}
    sandesh:
      introspectSslEnable: false
      sandeshCaCert: /etc/contrail/ssl/certs/ca-cert.pem
      sandeshCertfile: /etc/contrail/ssl/certs/server.pem
      sandeshKeyfile: /etc/contrail/ssl/private/server-privkey.pem
      sandeshSslEnable: false
    serviceInstance: {}
    services: {}
    session: {}
    stats: {}
    task: {}
    traceBuffSize: {}
    virtualHostInterface: {}
  agentModeType: dpdk
  cni: {}
  common:
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: node-role.kubernetes.io/control-plane
              operator: DoesNotExist
    containers:
    - image: 10.108.30.10:5000/atom-docker/cn2/bazel-build/dev/x86_64/contrail-vrouter-agent:master
      imagePullPolicy: IfNotPresent
      livenessProbe:
        failureThreshold: 3
        httpGet:
          host: 127.0.0.1
          path: /vrouter-health-check
          port: 9091
        initialDelaySeconds: 10
        periodSeconds: 20
        successThreshold: 1
        timeoutSeconds: 5
      name: contrail-vrouter-agent
      resources: {}
      startupProbe:
        failureThreshold: 3
        httpGet:
          host: 127.0.0.1
          path: /vrouter-health-check
          port: 9091
        initialDelaySeconds: 10
        periodSeconds: 20
        successThreshold: 1
        timeoutSeconds: 5
    - image: 10.108.30.10:5000/atom-docker/cn2/bazel-build/dev/x86_64/contrail-vrouter-dpdk:master
      imagePullPolicy: IfNotPresent
      name: contrail-vrouter-agent-dpdk
      resources:
        limits:
          hugepages-1Gi: 6Gi
          memory: 6Gi
        requests:
          hugepages-1Gi: 6Gi
          memory: 6Gi
    - env:
      - name: TELEMETRY_EXPORTER_SCHEME
        value: http
      - name: INTROSPECT_SCHEME
        value: http
      image: 10.108.30.10:5000/atom-docker/cn2/bazel-build/dev/x86_64/contrail-telemetry-exporter:master
      imagePullPolicy: IfNotPresent
      name: contrail-vrouter-telemetry-exporter
      resources: {}
    initContainers:
    - args:
      - sysctl -w net.ipv6.conf.default.addr_gen_mode=0 && sysctl -w net.ipv6.conf.all.addr_gen_mode=0
        && sysctl -w net.ipv6.conf.default.autoconf=0 && sysctl -w net.ipv6.conf.all.autoconf=0
        && echo -e "\nSuccessfully loaded kernel parameter using sysctl cli\n" ||
        echo -e "\nError in loading kernel parameter using sysctl cli\n"; modprobe
        tun && modprobe ipip && modprobe ip_tunnel && modprobe ip6_tunnel && modprobe
        mpls_gso && modprobe mpls_router && modprobe mpls_iptunnel && modprobe vrf
        && modprobe vxlan && modprobe fou && modprobe fou6 && echo -e "\nSuccessfully
        loaded kernel modules\n"|| echo -e "\nError in loadinfg kernel modules. Check
        whether kernel modules packages are installed or not.\nIf running OS is Ubuntu,
        Run following command and reboot  to enable kernel modules.\nsudo apt install
        linux-generic -y \n sudo apt install --reinstall linux-image-$(uname -r) -y;
        \n sudo apt install --reinstall linux-modules-$(uname -r) -y;\n sudo apt install
        --reinstall linux-modules-extra-$(uname -r) -y; \n" ; set -o pipefail && python3
        -u crpdconfig_generator/crpdconfig_generator.py evpn | tee -a "/var/log/contrail/cleanup.log"
        ;
      command:
      - /bin/sh
      - -c
      env:
      - name: NODE_NAME
        valueFrom:
          fieldRef:
            fieldPath: spec.nodeName
      - name: PYTHONUNBUFFERED
        value: "1"
      image: svl-artifactory.juniper.net/junos-docker-local/warthog/amd64/crpdconfig-generator:v21
      name: jcnr-evpn-conf
      resources: {}
      securityContext:
        capabilities:
          add:
          - SYS_MODULE
          - NET_ADMIN
          - SYS_PTRACE
        privileged: true
        runAsUser: 0
      volumeMounts:
      - mountPath: /etc/podinfo
        name: podinfo
      - mountPath: /var/lib/contrail
        name: var-lib-contrail
      - mountPath: /var/run
        name: var-run
      - mountPath: /var/run/contrail
        name: var-run-contrail
      - mountPath: /etc/contrail
        name: config-volume
      - mountPath: /var/crash
        name: var-crashes
      - mountPath: /var/log/contrail
        name: var-log-contrail
      - mountPath: /lib/modules
        name: lib-modules
    - image: 10.108.30.10:5000/atom-docker/cn2/bazel-build/dev/x86_64/contrail-init:master
      imagePullPolicy: IfNotPresent
      name: contrail-init
      resources: {}
    - image: 10.108.30.10:5000/atom-docker/cn2/bazel-build/dev/x86_64/contrail-vrouter-kernel-init-dpdk:master
      imagePullPolicy: IfNotPresent
      name: contrail-vrouter-kernel-init-dpdk
      resources: {}
  controlNodeInstance: contrail-control
  coreFilePath: /var/crash
  dpdk:
    cpuCoreMask: 2,3
    dpdkCommandAdditionalArgs: --yield_option 0
    dpdkUioDriver: vfio-pci
    hugePagesDir: /dev/hugepages
    l2TableAgeout: 60
    l2TableSize: "10240"
    mtu: 9000
    numServiceCtrlThreadCPU: 0
  headlessMode: true
  installCni: false
  interfaceLayer: l3
  interfaces:
  - ddp: auto
    level: l3
    name: enp3s0
    type: fabric
  kernel: {}
  logPath: /var/log/jcnr/
  metricsBindAddress: 127.0.0.1:18084
  qosEnable: false
  restoreInterfaces: false
  sriovLabelSelector: {}
  stormControlProfiles:
    rate_limit_pf1:
      bandwidth: {}
  vCommon: {}
