apiVersion: v1
data:
  kubeconfig: |
    apiVersion: v1
    clusters:
    - cluster:
        certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lJYXVKTy9COUtqSmN3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TXpFeU1qY3dPVE0zTkRCYUZ3MHpNekV5TWpRd09UUXlOREJhTUJVeApFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUURrcmw3UElmdG16aWYxN21TSmVVRnVJZHhtL3V6azkrMDd6d0NZWVJ2L3h5SmpmV1N5VE9nZ2FWNGIKT3lPaVVGZmp4T283NWZLVE1SVTh2S3RRWENTWVJ4YnZFeDRsajAzV2JDbllwZ3hleTJlRnF0OGo5WHpGMEZ6dwpkSWxla2JSL2hSemFFeVpoNXZ3ZEt1TGhVc09wUjBlcUlpcjR0UWNuaExzd1B0Ym8rNXFrVFpFOFR4MmI1eGw0CmdBWTA3VDd2cEp1ZHdZU2hwUHZib3JqWDFveHdkbWR4NXRwUVVkY0NBU0pXdXRrWUNISk9hWHp5RDVhZHF3SzkKdUdwK3pZbGpxRStqaTRIZUxqYzJZb1puN2VaajNBeGJFdVZBY0diUmpUWnlXenF2c1FIcTVKWjRpc3VRdTZyYgora2FxZVZlQ3JUZXBObGxIdW9wa0dUSjVmQ1Z2QWdNQkFBR2pXVEJYTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJRcEhDZkJOSE5aT1JVTXhJVHdhU0Zadm92NlNqQVYKQmdOVkhSRUVEakFNZ2dwcmRXSmxjbTVsZEdWek1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQXozb3VXTHVxUwp0WEc1OWpRQWRBajdadGxOOWJKN1dmV1lrRnplSmFhMU5vb0NTdnNvSU5QWVQ5M3RYYnE5MGlRYWZLWlZwMkhYCjhNMi92VVBaSlRDcFhCbXBiR0NUanVUY3RzYi8rTE5ZZW85UGk4WldUNlc3ZlI0ajl0aHdDQUJmdGxjY0pHcUEKbUpJOG5zejRncndhczNmNytwTnVhaDdIRUVEVGVHYkkvcmdrdFRaejUvdDd5ME1uYVYxbzlXbUFjZmtvQzFqcgpoNk9QaTFyVXpHcnZpRDhqSE8zc3FrVjRnVXYwdjgwcXBIVTR6UVZTUjJhRjJNWGsvdmxvVjB0VFpjZ08rUDZBCldKM01qMzlqZTR1Sm1uNkx3Y0RRdUtkWURsR0ZsbFRyY0g0UE03L3E4RENvdnpTOXhYdzNSTDdUR3B4VHJuUHMKa05hVm4rMk1vYVZKCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
        server: https://192.168.1.2:6443
      name: ""
    contexts: null
    current-context: ""
    kind: Config
    preferences: {}
    users: null
kind: ConfigMap
metadata:
  creationTimestamp: "2023-12-27T09:42:48Z"
  name: cluster-info
  namespace: kube-public
