apiVersion: v1
kind: Node
metadata:
  annotations:
    jcnr.juniper.net/internal-params: '{"routerMac": "48:5A:0D:BA:4E:BB"}'
    kubeadm.alpha.kubernetes.io/cri-socket: unix:///var/run/crio/crio.sock
    node.alpha.kubernetes.io/ttl: "0"
    projectcalico.org/IPv4Address: 192.168.2.3/24
    projectcalico.org/IPv4IPIPTunnelAddr: 10.244.35.128
    volumes.kubernetes.io/controller-managed-attach-detach: "true"
  creationTimestamp: "2023-12-27T09:45:53Z"
  labels:
    agent-mode: dpdk
    beta.kubernetes.io/arch: amd64
    beta.kubernetes.io/os: linux
    kubernetes.io/arch: amd64
    kubernetes.io/hostname: sharmag-k8s-dpdk-kubelet1-pnad30.englab.juniper.net
    kubernetes.io/os: linux
    node: kubelet1
  name: sharmag-k8s-dpdk-kubelet1-pnad30.englab.juniper.net
spec:
  podCIDR: 10.244.1.0/24
  podCIDRs:
  - 10.244.1.0/24
