apiVersion: scheduling.k8s.io/v1
description: Used for system critical pods that must not be moved from their current
  node.
kind: PriorityClass
metadata:
  creationTimestamp: "2023-12-27T09:42:47Z"
  name: system-node-critical
preemptionPolicy: PreemptLowerPriority
value: 2000001000
