apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: jcnr
    meta.helm.sh/release-namespace: default
  creationTimestamp: "2023-12-27T09:47:46Z"
  labels:
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: syslog-ng
  name: syslog-ng
  namespace: default
spec:
  clusterIP: 10.10.10.39
  clusterIPs:
  - 10.10.10.39
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: syslog-tcp
    port: 601
    protocol: TCP
    targetPort: 6601
  - name: syslog-udp
    port: 514
    protocol: UDP
    targetPort: 5514
  selector:
    app.kubernetes.io/name: syslog-ng
  sessionAffinity: None
  type: ClusterIP
