apiVersion: v1
data:
  sharmag-k8s-dpdk-kubelet1-pnad30.englab.juniper.net: 48:5A:0D:BA:4E:BB
  sharmag-k8s-master-pnad30.englab.juniper.net: 48:5A:0D:BA:25:CA
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: jcnr
    meta.helm.sh/release-namespace: default
  creationTimestamp: "2023-12-27T09:47:46Z"
  labels:
    app.kubernetes.io/managed-by: Helm
  name: router-mac-config
  namespace: jcnr
