apiVersion: v1
kind: Endpoints
metadata:
  annotations:
    endpoints.kubernetes.io/last-change-trigger-time: "2023-12-27T09:47:54Z"
  creationTimestamp: "2023-12-27T09:47:46Z"
  labels:
    app.kubernetes.io/managed-by: Helm
  name: webhook-service
  namespace: contrail-deploy
subsets:
- addresses:
  - ip: 192.168.1.3
    nodeName: sharmag-k8s-dpdk-kubelet1-pnad30.englab.juniper.net
    targetRef:
      kind: Pod
      name: contrail-k8s-deployer-67c445564f-8k7kk
      namespace: contrail-deploy
      uid: 535131bc-6134-4efc-b92a-d29cd8fcf540
  ports:
  - port: 29443
    protocol: TCP
