apiVersion: v1
data:
  ClusterConfiguration: |
    apiServer:
      certSANs:
      - 10.108.34.77
      - 192.168.1.2
      extraArgs:
        authorization-mode: Node,RBAC
      timeoutForControlPlane: 4m0s
    apiVersion: kubeadm.k8s.io/v1beta3
    certificatesDir: /etc/kubernetes/pki
    clusterName: kubernetes
    controllerManager: {}
    dns: {}
    etcd:
      local:
        dataDir: /var/lib/etcd
        serverCertSANs:
        - 10.108.34.77
        - 192.168.1.2
        - localhost
        - 127.0.0.1
    imageRepository: registry.englab.juniper.net/jfrog-repo/hosted_docker_images
    kind: ClusterConfiguration
    kubernetesVersion: v1.28.2
    networking:
      dnsDomain: cluster.local
      podSubnet: 10.244.0.0/16
      serviceSubnet: 10.10.10.0/24
    scheduler: {}
kind: ConfigMap
metadata:
  creationTimestamp: "2023-12-27T09:42:47Z"
  name: kubeadm-config
  namespace: kube-system
