apiVersion: v1
kind: Endpoints
metadata:
  creationTimestamp: "2023-12-27T09:43:05Z"
  labels:
    k8s-app: kube-dns
    kubernetes.io/cluster-service: "true"
    kubernetes.io/name: CoreDNS
  name: kube-dns
  namespace: kube-system
subsets:
- notReadyAddresses:
  - ip: 10.244.100.193
    nodeName: sharmag-k8s-master-pnad30.englab.juniper.net
    targetRef:
      kind: Pod
      name: coredns-56bc94896d-26v92
      namespace: kube-system
      uid: cfe61321-a923-47b5-ab2e-de122e60e13f
  - ip: 10.244.100.194
    nodeName: sharmag-k8s-master-pnad30.englab.juniper.net
    targetRef:
      kind: Pod
      name: coredns-56bc94896d-7txm9
      namespace: kube-system
      uid: 2a7c1618-0dad-4e02-87e9-211dea179ad7
  ports:
  - name: dns-tcp
    port: 53
    protocol: TCP
  - name: dns
    port: 53
    protocol: UDP
  - name: metrics
    port: 9153
    protocol: TCP
