apiVersion: events.k8s.io/v1
deprecatedCount: 1
deprecatedFirstTimestamp: "2024-01-09T19:00:48Z"
deprecatedLastTimestamp: "2024-01-09T19:00:48Z"
deprecatedSource:
  component: kubelet
  host: minikube
eventTime: null
kind: Event
metadata:
  creationTimestamp: "2024-01-09T19:00:48Z"
  name: katafygio-88f5d8f5f-4pwh5.17a8c2fc7f07437f
  namespace: default
  uid: 142fe83d-e527-42fc-bfb4-43bd962b6592
note: Pulling image "sharmag07/katafygio:latest"
reason: Pulling
regarding:
  apiVersion: v1
  fieldPath: spec.containers{katafygio}
  kind: Pod
  name: katafygio-88f5d8f5f-4pwh5
  namespace: default
  resourceVersion: "1321268"
  uid: 277abf8b-b990-46fc-bd66-30e0c27d8eca
type: Normal
