apiVersion: events.k8s.io/v1
deprecatedCount: 1
deprecatedFirstTimestamp: "2024-01-09T18:11:57Z"
deprecatedLastTimestamp: "2024-01-09T18:11:57Z"
deprecatedSource:
  component: replicaset-controller
eventTime: null
kind: Event
metadata:
  creationTimestamp: "2024-01-09T18:11:57Z"
  name: katafygio-88f5d8f5f.17a8c051f2726c6f
  namespace: default
  uid: f6c674cd-7bbd-443a-8380-d284320149d6
note: 'Created pod: katafygio-88f5d8f5f-zkfs4'
reason: SuccessfulCreate
regarding:
  apiVersion: apps/v1
  kind: ReplicaSet
  name: katafygio-88f5d8f5f
  namespace: default
  resourceVersion: "1318496"
  uid: 2acbf894-eb33-4db6-aab7-cf0b915ced6b
type: Normal
