apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2023-11-02T06:50:24Z"
  generateName: go-app-697df4b455-
  labels:
    app: go-app
    pod-template-hash: 697df4b455
  name: go-app-697df4b455-j7lrl
  namespace: default
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: go-app-697df4b455
    uid: 3c3860ef-983e-4f62-a807-7fa6ee67c3ab
  uid: c66b1aaa-d693-4cc3-b940-8a7a7a58da31
spec:
  containers:
  - image: sharmag07/url-short:a2
    imagePullPolicy: IfNotPresent
    name: go-app
    ports:
    - containerPort: 8090
      protocol: TCP
    resources:
      limits:
        cpu: 800m
        memory: 128Mi
      requests:
        cpu: 800m
        memory: 128Mi
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-wsbtf
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: minikube
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: kube-api-access-wsbtf
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2023-11-02T06:50:24Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2024-01-08T10:10:50Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2024-01-08T10:10:50Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2023-11-02T06:50:24Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://548bf6b44b3c75dd1bceec8e0f68df4f7d0b0188ce7311f05d4222fa461f29d7
    image: sharmag07/url-short:a2
    imageID: docker-pullable://sharmag07/url-short@sha256:790976208330dbb1941cb31248c7bb64d4cdd4c04e3f8e87ef9eceb5f7c0493f
    lastState:
      terminated:
        containerID: docker://87aa2fa65d8fe3ade80449cfb29cc58bca5da4191779765a4523cf925185d245
        exitCode: 2
        finishedAt: "2024-01-08T10:10:33Z"
        reason: Error
        startedAt: "2024-01-05T07:57:00Z"
    name: go-app
    ready: true
    restartCount: 7
    started: true
    state:
      running:
        startedAt: "2024-01-08T10:10:48Z"
  hostIP: 192.168.49.2
  phase: Running
  podIP: 10.244.0.167
  podIPs:
  - ip: 10.244.0.167
  qosClass: Guaranteed
  startTime: "2023-11-02T06:50:24Z"
