apiVersion: coordination.k8s.io/v1
kind: Lease
metadata:
  creationTimestamp: "2024-01-02T05:32:12Z"
  name: cert-manager-controller
  namespace: kube-system
  uid: a0122e1b-2f0c-46bc-a732-0a157008771f
spec:
  acquireTime: "2024-01-02T05:32:12.092115Z"
  holderIdentity: cert-manager-7476c8fcf4-fzmh5-external-cert-manager-controller
  leaseDurationSeconds: 60
  leaseTransitions: 0
  renewTime: "2024-01-09T19:12:46.285498Z"
